apiVersion: frrcontroller.nocsys.cn/v1alpha1
kind: Frr
metadata:
  name: example-frr
spec:
  deploymentName: example-frr
  replicas: 1
  image: nocsyscn/ovnk-frr:8.5.1
  initConfigImage: nocsyscn/frr_conf:0.2
  asNumber: 65001
  neighbors:
  - 172.20.0.5
